import differential_geometry_immersions_minimal_prescribed_lemma_canonical_lane_mathlib.GateLemmas
import differential_geometry_immersions_minimal_prescribed_lemma_canonical_lane_mathlib.FinalTheorem
